# Generated by Django 4.1.1 on 2022-09-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='module',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
